- name: Replace APT source list
  replace:
    dest=/etc/apt/sources.list
    regexp='us.archive.ubuntu.com'
    replace='ubuntu.cs.nctu.edu.tw'
    backup=yes

- name: Update APT Cache
  apt: update_cache=yes

- name: Install required packages
  apt: name={{ item }} state=present
  with_items:
    - vim
    - tmux
    - git
    - htop
    - software-properites-common
