- name: Install ntp daemon
  apt: name=ntp
- name: Change timezone Asia/Taipei
  copy: src=/usr/share/zoneinfo/Asia/Taipei dest=/etc/localtime

# XXX: run_once is useless
- name: Write to hardware
  command: 'hwclock -w'
  run_once: true
