- hosts: all
  sudo: true
  tasks:
    - include: tasks/apt.yml
    - name: Install required packages
      apt: name={{ item }} state=present
      with_items:
        - vim
        - tmux
        - git
        - htop
    - include: tasks/momorc.yml
