# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "parallels/ubuntu-14.04"
  config.vm.hostname = "opennet"

  # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
  config.vm.define :opennet do |opennet|
  end

  # TODO: Change username from 'vagrant' to 'pichuang'
  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'

  config.vm.synced_folder "/Users/roan/PycharmProjects/opennet_workstation/opennet", "/root/opennet", owner: "root", group: "root"

  config.vm.provider "parallels" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  #Configuration Management -- Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
    ansible.inventory_path = "provisioning/hosts"
    ansible.sudo = "true"
  end
end
