# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "parallels/ubuntu-14.04"
  config.vm.hostname = "ops-dev"
  #config.vm.network :private_network, ip: "10.211.55.91"

  # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
  config.vm.define :ops-dev do |ops-dev|
  end

  # TODO: Change username from 'vagrant' to 'pichuang'
  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'

  #Configuration Management -- Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
    ansible.inventory_path = "provisioning/hosts"
    ansible.sudo = "true"
  end
end
